common: &common
  adapter: postgresql
  encoding: utf8
  reconnect: false
  pool: 5
  host: localhost

development:
  <<: *common
  database: pressplay-test
  username: abhinemani
  password: 
test:
  <<: *common
  database: link_manager_test
  username: root
  password: '123'

production:
  <<: *common
  database: link_manager_production
  username: root
  password: '123'
